
auth.token=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

defaults.org=fofensoft-srl
defaults.project=react-native

defaults.url=https://sentry.io/
